[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F401RETx"

[target.'cfg(all(target_arch = "riscv32"))']
# runner = "probe-rs run --chip CH32V307"
runner = "wlink flash --enable-sdi-print --watch-serial -v"

rustflags = [
#   "-C", "linker=flip-link",
#   # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
#   # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
#   "-C", "link-arg=--nmagic",
#   "-C", "link-arg=--verbose",
#   # "-C", "link-arg=-Tdefmt.x",
]

[build]
# target = "thumbv7em-none-eabi"
target = "riscv32imc-unknown-none-elf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"

# [env]
# DEFMT_LOG = "trace"
# DEFMT_LOG = "info"
[profile.release]
strip = false   # symbols are not flashed to the microcontroller, so don't strip them.
lto = true
opt-level = "z" # Optimize for size.