[package]
name = "embassy-preempt-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-preempt-platform = { path = "../embassy-preempt-platform"}

[features]
default = ["stm32f401re"]
stm32f401re = []