[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F401RETx with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F401RETx"

rustflags = [
  "-C", "linker=flip-link",
  # "-C", "link-arg=-Tlink.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",
]

[build]
target = "riscv32imc-unknown-none-elf"
# target = "thumbv7em-none-eabi"

[alias]
rb = "run --bin"
rrb = "run --release --bin"

[env]
# the config of max_mem_part
OS_MAX_MEM_PART = "5"
# about message
OS_Q_EN = "0"
OS_MAX_QS = "0"
OS_MBOX_EN = "0"
OS_SEM_EN = "0"
OS_MUTEX_EN = "0"
OS_EVENT_NAME_EN = "0"
OS_LOWEST_PRIO = "63"
DEFMT_LOG = "trace" # <- can change to info, warn, or error. to print info